export const SRI_LANKAN_DISTRICTS = [
  { district: 'Colombo', fee: 350 },
  { district: 'Gampaha', fee: 400 },
  { district: 'Kalutara', fee: 450 },
  { district: 'Kandy', fee: 500 },
  { district: 'Matale', fee: 550 },
  { district: 'Nuwara Eliya', fee: 600 },
  { district: 'Galle', fee: 500 },
  { district: 'Matara', fee: 550 },
  { district: 'Hambantota', fee: 600 },
  { district: 'Jaffna', fee: 700 },
  { district: 'Kilinochchi', fee: 700 },
  { district: 'Mannar', fee: 700 },
  { district: 'Vavuniya', fee: 650 },
  { district: 'Mullaitivu', fee: 700 },
  { district: 'Batticaloa', fee: 650 },
  { district: 'Ampara', fee: 650 },
  { district: 'Trincomalee', fee: 650 },
  { district: 'Kurunegala', fee: 500 },
  { district: 'Puttalam', fee: 550 },
  { district: 'Anuradhapura', fee: 600 },
  { district: 'Polonnaruwa', fee: 600 },
  { district: 'Badulla', fee: 600 },
  { district: 'Moneragala', fee: 650 },
  { district: 'Ratnapura', fee: 550 },
  { district: 'Kegalle', fee: 500 }
];

export const INITIAL_CATEGORIES = [
  {
    name: 'Baby Care',
    slug: 'baby-care',
    description: 'Gentle, dermatologist-approved skincare and hygiene essentials for your little one’s delicate skin.',
    image: '/products/img2.jpg',
    featured: true,
    active: true,
    order: 1
  },
  {
    name: 'Mom Care',
    slug: 'mom-care',
    description: 'Nourishing, restorative self-care and postpartum wellness products crafted specifically for mothers.',
    image: '/products/img16.avif',
    featured: true,
    active: true,
    order: 2
  },
  {
    name: 'Feeding & Nursing',
    slug: 'feeding-nursing',
    description: 'BPA-free accessories, organic nursing cushions, and ergonomic bonding aids.',
    image: '/products/img28.jpg',
    featured: true,
    active: true,
    order: 3
  },
  {
    name: 'Sleep & Snuggle',
    slug: 'sleep-snuggle',
    description: 'Ultra-soft organic muslin swaddles, breathable sleep sacks, and soothing lullaby blankets.',
    image: '/products/img19.webp',
    featured: true,
    active: true,
    order: 4
  },
  {
    name: 'Bath & Care',
    slug: 'bath-care',
    description: 'Tear-free shampoos, organic bamboo hooded towels, and gentle bath-time comfort essentials.',
    image: '/products/img18.webp',
    featured: true,
    active: true,
    order: 5
  },
  {
    name: 'Clothing',
    slug: 'clothing',
    description: 'GOTS-certified 100% organic cotton rompers, footies, and matching mom & mini loungewear.',
    image: '/products/img3.webp',
    featured: true,
    active: true,
    order: 6
  },
  {
    name: 'Toys & Gifts',
    slug: 'toys-gifts',
    description: 'Non-toxic beechwood teethers, heirloom soft plushies, and beautifully packaged newborn gift sets.',
    image: '/products/img1.webp',
    featured: true,
    active: true,
    order: 7
  },
  {
    name: 'Baby Essentials',
    slug: 'baby-essentials',
    description: 'Everyday must-haves, diapering accessories, thermal bags, and safety essentials for modern parents.',
    image: '/products/img40.jpg',
    featured: true,
    active: true,
    order: 8
  }
];

export const INITIAL_PRODUCTS = [
  {
    name: 'Sweet Blossom Newborn Baby Hamper Gift Set',
    slug: 'sweet-blossom-newborn-baby-hamper-gift-set',
    shortDescription: 'Delightful newborn gift hamper with hooded blanket, cotton nappies, beanie, and swaddle.',
    description: 'Delightful luxury newborn gift hamper featuring a cotton jersey hooded blanket, 6-pack pure cotton nappies, 3-pack wash cloths, knotted baby beanie, cozy booties, and an organic muslin rainbow swaddle.',
    price: 5490,
    discountPrice: 4890,
    categorySlug: 'toys-gifts',
    gender: 'girl',
    images: ['/products/img1.webp'],
    stock: 20,
    sku: 'BC-GIFT-001',
    brand: 'Butterfly Care Gift',
    ageGroup: '0-6 months',
    sizes: ['Newborn (0-6M)'],
    colors: ['Sweet Pink Blossom'],
    materials: '100% Cotton Jersey & Organic Muslin',
    careInstructions: 'Gentle machine wash cold. Do not bleach.',
    rating: 5.0,
    reviewCount: 46,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Gentle Baby Daily Skincare & Bath Care Kit (4-Piece Set)',
    slug: 'gentle-baby-daily-skincare-bath-kit',
    shortDescription: 'Complete 4-piece hypoallergenic baby care set: shampoo, wash, lotion, and diaper cream.',
    description: 'Complete hypoallergenic daily essentials bundle: Diaper Rash Cream with Shea Butter & Jojoba, Baby Shampoo & Body Wash, Calming Baby Massage Oil with Sweet Almond, and Hydrating Baby Body Lotion.',
    price: 4450,
    discountPrice: 3950,
    categorySlug: 'bath-care',
    gender: 'unisex',
    images: ['/products/img2.jpg'],
    stock: 25,
    sku: 'BC-BATH-002',
    brand: 'Butterfly Care Pure',
    ageGroup: '0+ months',
    sizes: ['Full Care Set'],
    colors: ['Pure White'],
    materials: 'Colloidal Oat, Sweet Almond Oil, Shea Butter, Zinc Oxide',
    careInstructions: 'Store in a cool dry place.',
    rating: 4.9,
    reviewCount: 32,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Pastel Blossom Floral Baby Girl Cotton Frock',
    slug: 'pastel-blossom-floral-baby-girl-cotton-frock',
    shortDescription: 'Charming lilac floral print baby frock with puff sleeves and tie bow.',
    description: 'Charming lilac floral print baby frock made from 100% breathable cotton with puff sleeves, button-back closure, and a delicate tie bow at the waist.',
    price: 1890,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img3.webp'],
    stock: 18,
    sku: 'BC-GIRL-003',
    brand: 'Butterfly Care',
    ageGroup: '0-24 months',
    sizes: ['0-3M', '3-6M', '6-12M', '1-2Y'],
    colors: ['Lilac Blossom'],
    materials: '100% Premium Cotton',
    careInstructions: 'Machine wash cold inside out.',
    rating: 4.8,
    reviewCount: 24,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Hand-Smocked Vintage White Baby Dress with Bonnet',
    slug: 'hand-smocked-vintage-white-baby-dress-with-bonnet',
    shortDescription: 'Timeless heirloom hand-smocked white cotton dress with matching floral bonnet.',
    description: 'Timeless heirloom hand-smocked white cotton dress featuring delicate pastel floral embroidery, lace-trimmed hem, and an adorable matching tie bonnet.',
    price: 3450,
    discountPrice: 2990,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img4.webp'],
    stock: 15,
    sku: 'BC-GIRL-004',
    brand: 'Butterfly Care Heirloom',
    ageGroup: '0-18 months',
    sizes: ['0-3M', '3-6M', '6-12M', '12-18M'],
    colors: ['Vintage White'],
    materials: '100% Soft Combed Cotton',
    careInstructions: 'Hand wash recommended or delicate machine cycle.',
    rating: 5.0,
    reviewCount: 39,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Organic Cotton Short-Sleeve Bodysuit Multipack (Set of 5)',
    slug: 'organic-cotton-short-sleeve-bodysuit-multipack',
    shortDescription: 'Set of 5 ultra-soft combed organic cotton bodysuits in gentle earthy neutral tones.',
    description: 'Pack of 5 ultra-soft combed organic cotton bodysuits in gentle earthy hues: teddy bear print, warm oat, cream, and biscuit tan with snap button fastenings.',
    price: 3850,
    discountPrice: 3450,
    categorySlug: 'clothing',
    gender: 'unisex',
    images: ['/products/img5.webp'],
    stock: 30,
    sku: 'BC-UNI-005',
    brand: 'Butterfly Care Basics',
    ageGroup: '0-18 months',
    sizes: ['0-3M', '3-6M', '6-12M', '12-18M'],
    colors: ['Neutral Earthy Mix'],
    materials: '100% GOTS Organic Cotton',
    careInstructions: 'Machine wash warm. Tumble dry low.',
    rating: 4.9,
    reviewCount: 52,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Baby Boy Seaside Striped Resort Pajama Set',
    slug: 'baby-boy-seaside-striped-resort-pajama-set',
    shortDescription: 'Classic sage & ocean blue vertical striped button-up shirt and shorts set.',
    description: 'Crisp sage and ocean blue vertical striped two-piece lounge and play set featuring a notch-collar button-up shirt with matching elasticated shorts.',
    price: 1950,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img6.jpg'],
    stock: 22,
    sku: 'BC-BOY-006',
    brand: 'Butterfly Care Boy',
    ageGroup: '3-36 months',
    sizes: ['3-6M', '6-12M', '1-2Y', '2-3Y'],
    colors: ['Ocean Stripe'],
    materials: '100% Breathable Cotton',
    careInstructions: 'Machine wash cold.',
    rating: 4.8,
    reviewCount: 28,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Botanical Meadow Green Smocked Peter-Pan Frock',
    slug: 'botanical-meadow-green-smocked-peter-pan-frock',
    shortDescription: 'Sage floral smocked frock with ruffled cap sleeves and Peter Pan collar.',
    description: 'Earthy sage green frock adorned with wildflowers, hand-detailed honeycomb smocking across the chest, and ruffled Peter Pan collar.',
    price: 2290,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img7.webp'],
    stock: 16,
    sku: 'BC-GIRL-007',
    brand: 'Butterfly Care',
    ageGroup: '0-36 months',
    sizes: ['0-6M', '6-12M', '1-2Y', '2-3Y'],
    colors: ['Meadow Sage Green'],
    materials: '100% Pure Cotton',
    careInstructions: 'Machine wash cold with gentle detergent.',
    rating: 4.9,
    reviewCount: 31,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Terracotta Muslin Little Driver Play Set',
    slug: 'terracotta-muslin-little-driver-play-set',
    shortDescription: 'Double gauze cotton muslin button-down with embroidered car and shorts.',
    description: 'Breathable double gauze cotton muslin button-down shirt with little embroidered vintage car and matching relaxed shorts in warm terracotta.',
    price: 2150,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img8.webp'],
    stock: 20,
    sku: 'BC-BOY-008',
    brand: 'Butterfly Care Boy',
    ageGroup: '6-48 months',
    sizes: ['6-12M', '1-2Y', '2-3Y', '3-4Y'],
    colors: ['Warm Terracotta'],
    materials: '100% Double Gauze Cotton Muslin',
    careInstructions: 'Machine wash cold. Line dry recommended.',
    rating: 5.0,
    reviewCount: 44,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Cozy Cotton Cargo Jogger Pants (2-Pack Duo)',
    slug: 'cozy-cotton-cargo-jogger-pants-2-pack',
    shortDescription: 'Pack of 2 comfortable elasticated cargo joggers in caramel and slate charcoal.',
    description: 'Set of 2 everyday play joggers in warm caramel brown and charcoal slate. Features deep cargo side pockets, stretchy waistband, and roll-up cuffs.',
    price: 1990,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img9.webp'],
    stock: 24,
    sku: 'BC-BOY-009',
    brand: 'Butterfly Care Boy',
    ageGroup: '6-48 months',
    sizes: ['6-12M', '1-2Y', '2-3Y', '3-4Y'],
    colors: ['Caramel & Charcoal'],
    materials: '95% Soft Cotton, 5% Elastane',
    careInstructions: 'Machine wash warm.',
    rating: 4.8,
    reviewCount: 22,
    featured: false,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Baby Boy Dinosaur Embroidered Classic Blue Polo',
    slug: 'baby-boy-dinosaur-embroidered-classic-blue-polo',
    shortDescription: 'Ocean blue pique cotton polo with embroidered Baby Saurus motif.',
    description: 'Ocean blue pique cotton polo shirt featuring tipped ribbed collar, number 7 sleeve patch, and an adorable white embroidered Baby Saurus triceratops motif.',
    price: 1490,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img10.jpg'],
    stock: 26,
    sku: 'BC-BOY-010',
    brand: 'Butterfly Care Boy',
    ageGroup: '6-48 months',
    sizes: ['6-12M', '1-2Y', '2-3Y', '3-4Y'],
    colors: ['Ocean Sky Blue'],
    materials: '100% Pique Combed Cotton',
    careInstructions: 'Machine wash cold.',
    rating: 4.9,
    reviewCount: 35,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Gentleman Baby Boy Suspender & Bowtie Formal Set',
    slug: 'gentleman-baby-boy-suspender-bowtie-formal-set',
    shortDescription: 'Dapper striped button-up shirt with navy bowtie and suspender shorts.',
    description: 'Dapper party outfit featuring a white micro-striped collared shirt with detachable navy bow tie and tailored navy suspender shorts with buttons.',
    price: 3450,
    discountPrice: 2950,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img11.jpg'],
    stock: 18,
    sku: 'BC-BOY-011',
    brand: 'Butterfly Care Boy',
    ageGroup: '0-36 months',
    sizes: ['0-6M', '6-12M', '1-2Y', '2-3Y'],
    colors: ['Navy & White'],
    materials: '100% Cotton Shirt & Chino Twill Shorts',
    careInstructions: 'Dry clean or gentle cycle machine wash.',
    rating: 5.0,
    reviewCount: 41,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Sky Blue Gingham Checkered Toddler Shirt',
    slug: 'sky-blue-gingham-checkered-toddler-shirt',
    shortDescription: 'Pastel sky blue and white gingham check button-down shirt with chest pocket.',
    description: 'Fresh pastel sky blue and white gingham check button-down shirt crafted from soft lightweight cotton with short sleeves and front chest pocket.',
    price: 1590,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img12.jpg'],
    stock: 22,
    sku: 'BC-BOY-012',
    brand: 'Butterfly Care Boy',
    ageGroup: '6-48 months',
    sizes: ['6-12M', '1-2Y', '2-3Y', '3-4Y'],
    colors: ['Sky Blue Gingham'],
    materials: '100% Cotton Poplin',
    careInstructions: 'Machine wash cold.',
    rating: 4.8,
    reviewCount: 19,
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Mint Blossom Smocked Floral Heirloom Baby Dress',
    slug: 'mint-blossom-smocked-floral-heirloom-baby-dress',
    shortDescription: 'Mint green cotton party frock with smocked embroidery bodice and puff sleeves.',
    description: 'Soft mint green cotton party frock filled with delicate pink blossom prints, traditional smocked embroidery bodice, and gentle puff sleeves.',
    price: 2750,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img13.jpg'],
    stock: 14,
    sku: 'BC-GIRL-013',
    brand: 'Butterfly Care Heirloom',
    ageGroup: '0-24 months',
    sizes: ['0-3M', '3-6M', '6-12M', '1-2Y'],
    colors: ['Mint Rose Blossom'],
    materials: '100% Fine Combed Cotton',
    careInstructions: 'Hand wash or gentle machine wash.',
    rating: 5.0,
    reviewCount: 48,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Pastel Smocked Cotton Sun Dress Duo with Bow Sandals',
    slug: 'pastel-smocked-cotton-sun-dress-duo',
    shortDescription: 'Pair of smocked pink & sky blue seersucker dresses with white bow sandals.',
    description: 'Delightful summer ensemble pair: powder pink striped and seafoam seersucker smocked sundresses with white bow detail open-toe sandals.',
    price: 3250,
    discountPrice: 2890,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img14.webp'],
    stock: 12,
    sku: 'BC-GIRL-014',
    brand: 'Butterfly Care',
    ageGroup: '0-24 months',
    sizes: ['0-6M', '6-12M', '1-2Y'],
    colors: ['Pastel Duo'],
    materials: '100% Seersucker Cotton',
    careInstructions: 'Machine wash cold.',
    rating: 4.9,
    reviewCount: 33,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Shimmer Rose Gold Pleated Baby Girl Party Dress',
    slug: 'shimmer-rose-gold-pleated-baby-girl-party-dress',
    shortDescription: 'Metallic rose gold occasion dress with accordion pleats and cotton lining.',
    description: 'Radiant metallic rose gold occasion dress with accordion micro-pleating, sleeveless silhouette, button back, and cotton lining for irritation-free celebration wear.',
    price: 3250,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img15.jpg'],
    stock: 15,
    sku: 'BC-GIRL-015',
    brand: 'Butterfly Care Occasions',
    ageGroup: '3-36 months',
    sizes: ['3-6M', '6-12M', '1-2Y', '2-3Y'],
    colors: ['Rose Gold Shimmer'],
    materials: 'Shimmer Lurex Voile with 100% Cotton Lining',
    careInstructions: 'Hand wash cold or dry clean.',
    rating: 4.9,
    reviewCount: 27,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Comfort Bamboo Nursing & Maternal Care Loungewear',
    slug: 'comfort-bamboo-nursing-maternal-care-loungewear',
    shortDescription: 'Silky organic bamboo maternity and nursing lounge set for mothers.',
    description: 'Luxuriously soft organic bamboo loungewear designed for maternity comfort and easy nursing access during postpartum recovery and bedtime bonding.',
    price: 4500,
    discountPrice: 3950,
    categorySlug: 'mom-care',
    gender: 'mom',
    images: ['/products/img16.avif'],
    stock: 20,
    sku: 'BC-MOM-016',
    brand: 'Butterfly Care Mama',
    ageGroup: 'Mothers',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Heather Mauve'],
    materials: '95% Organic Bamboo Viscose, 5% Spandex',
    careInstructions: 'Machine wash cold. Lay flat to dry.',
    rating: 5.0,
    reviewCount: 50,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Pure Organic Chamomile Calming Baby Body Wash (300ml)',
    slug: 'pure-organic-chamomile-calming-baby-body-wash',
    shortDescription: 'Gentle tear-free botanical cleanser formulated for newborn skin and hair.',
    description: 'Infused with organic chamomile and calendula flower extract, this soothing baby wash gently cleanses while preserving skin hydration.',
    price: 1950,
    categorySlug: 'bath-care',
    gender: 'unisex',
    images: ['/products/img17.webp'],
    stock: 25,
    sku: 'BC-BW-017',
    brand: 'Butterfly Care Pure',
    ageGroup: '0-36 months',
    sizes: ['300ml'],
    colors: ['Natural Chamomile'],
    materials: 'Organic Chamomile & Calendula Extract',
    careInstructions: 'Apply small amount on damp washcloth or palm.',
    rating: 4.9,
    reviewCount: 38,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Silky Soft Organic Bamboo Hooded Baby Bath Towel',
    slug: 'silky-soft-organic-bamboo-hooded-baby-bath-towel',
    shortDescription: 'Ultra-absorbent 500GSM organic bamboo hooded towel with cute ears.',
    description: 'Wrap your little one in plush, quick-drying organic bamboo terry cloth. Highly absorbent, naturally antibacterial, and ultra-gentle on delicate newborn skin.',
    price: 2990,
    discountPrice: 2650,
    categorySlug: 'bath-care',
    gender: 'unisex',
    images: ['/products/img18.webp'],
    stock: 22,
    sku: 'BC-TOW-018',
    brand: 'Butterfly Care Pure',
    ageGroup: '0-36 months',
    sizes: ['90cm x 90cm'],
    colors: ['Oatmeal Cream'],
    materials: '100% Organic Bamboo Viscose Terry',
    careInstructions: 'Machine wash warm with mild detergent.',
    rating: 5.0,
    reviewCount: 43,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: '4-Layer Organic Muslin Dream Swaddle Blanket (Pack of 3)',
    slug: '4-layer-organic-muslin-dream-swaddle-blanket-pack',
    shortDescription: 'Breathable, temperature-regulating organic cotton muslin swaddle blankets.',
    description: 'Set of 3 extra-large 120cm x 120cm breathable organic cotton muslin swaddles. Becomes softer with every wash for restful sleep and snuggle times.',
    price: 4950,
    discountPrice: 4450,
    categorySlug: 'sleep-snuggle',
    gender: 'unisex',
    images: ['/products/img19.webp'],
    stock: 30,
    sku: 'BC-SW-019',
    brand: 'Butterfly Care Sleep',
    ageGroup: '0-24 months',
    sizes: ['120cm x 120cm'],
    colors: ['Pastel Butterfly Trio'],
    materials: '100% GOTS Certified Organic Cotton Muslin',
    careInstructions: 'Machine wash gentle. Tumble dry low.',
    rating: 4.9,
    reviewCount: 56,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Pastel Butterfly Floral Tiered Cotton Sun Dress',
    slug: 'pastel-butterfly-floral-tiered-cotton-sun-dress',
    shortDescription: 'Delicate pastel floral tiered summer dress with ruffled flutter sleeves.',
    description: 'Charming tiered baby girl dress in lightweight breathable cotton poplin featuring pastel butterfly and blossom prints with mother-of-pearl buttons.',
    price: 1950,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img20.webp'],
    stock: 18,
    sku: 'BC-GIRL-020',
    brand: 'Butterfly Care',
    ageGroup: '0-36 months',
    sizes: ['0-6M', '6-12M', '1-2Y', '2-3Y'],
    colors: ['Butterfly Blossom'],
    materials: '100% Pure Cotton Poplin',
    careInstructions: 'Machine wash cold.',
    rating: 4.9,
    reviewCount: 31,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Linen Blend Baby Boy Mandarin Collar Henley Shirt',
    slug: 'linen-blend-baby-boy-mandarin-collar-henley-shirt',
    shortDescription: 'Airy linen-cotton blend short-sleeve shirt with wooden button placket.',
    description: 'Sophisticated relaxed linen-cotton shirt featuring a mandarin collar, buttoned chest pocket, and gentle breathable weave for tropical comfort.',
    price: 1790,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img21.webp'],
    stock: 24,
    sku: 'BC-BOY-021',
    brand: 'Butterfly Care Boy',
    ageGroup: '6-48 months',
    sizes: ['6-12M', '1-2Y', '2-3Y', '3-4Y'],
    colors: ['Sage Mist'],
    materials: '55% French Linen, 45% Organic Cotton',
    careInstructions: 'Machine wash cold, line dry.',
    rating: 4.8,
    reviewCount: 25,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Nourishing Motherhood Belly & Stretchmark Botanical Oil (100ml)',
    slug: 'nourishing-motherhood-belly-stretchmark-botanical-oil',
    shortDescription: 'Rich botanical blend of Rosehip, Marula, and Vitamin E for pregnancy elasticity.',
    description: 'Formulated with utmost love for expecting and new mamas. Packed with essential fatty acids and natural antioxidants that encourage elasticity and relieve stretching skin.',
    price: 3950,
    discountPrice: 3490,
    categorySlug: 'mom-care',
    gender: 'mom',
    images: ['/products/img22.webp'],
    stock: 20,
    sku: 'BC-MO-022',
    brand: 'Butterfly Care Mama',
    ageGroup: 'Mothers',
    sizes: ['100ml'],
    colors: ['Golden Rose'],
    materials: 'Cold-pressed Rosehip Seed Oil, Marula Oil, Tocopherol',
    careInstructions: 'Massage twice daily in circular motions.',
    rating: 5.0,
    reviewCount: 54,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Heirloom Knitted Pointelle Baby Cardigan & Beanie Set',
    slug: 'heirloom-knitted-pointelle-baby-cardigan-beanie-set',
    shortDescription: 'Cozy combed cotton knit cardigan with wooden buttons and matching beanie.',
    description: 'Traditional pointelle knit baby cardigan and beanie duo crafted from combed cotton yarn. Keeps baby comfortably warm for outings and hospital departures.',
    price: 2850,
    categorySlug: 'clothing',
    gender: 'unisex',
    images: ['/products/img23.jpg'],
    stock: 16,
    sku: 'BC-KNIT-023',
    brand: 'Butterfly Care Heirloom',
    ageGroup: '0-18 months',
    sizes: ['0-3M', '3-6M', '6-12M', '12-18M'],
    colors: ['Biscuit Cream'],
    materials: '100% Combed Cotton Knit',
    careInstructions: 'Hand wash cold or gentle machine cycle. Dry flat.',
    rating: 5.0,
    reviewCount: 37,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Natural Wooden Sensory Teether & Rattle Gift Set',
    slug: 'natural-wooden-sensory-teether-rattle-gift-set',
    shortDescription: 'Chemical-free natural beechwood teether ring with soft crochet bell.',
    description: 'Handcrafted non-toxic beechwood teething rings with soft cotton crochet ears. Provides safe teething relief and tactile sensory exploration for infants.',
    price: 1450,
    categorySlug: 'toys-gifts',
    gender: 'unisex',
    images: ['/products/img24.webp'],
    stock: 28,
    sku: 'BC-TOY-024',
    brand: 'Butterfly Care Gift',
    ageGroup: '3-18 months',
    sizes: ['Standard'],
    colors: ['Natural Beechwood & Sage'],
    materials: 'Organic Beechwood & 100% Cotton Yarn',
    careInstructions: 'Wipe clean with a damp cloth.',
    rating: 4.9,
    reviewCount: 29,
    featured: false,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Soft Ribbed Cotton Zip Sleepsuit with Mitten Cuffs',
    slug: 'soft-ribbed-cotton-zip-sleepsuit-mitten-cuffs',
    shortDescription: '2-way zipper ribbed cotton sleep & play onesie with foldover anti-scratch mittens.',
    description: 'Effortless diaper changes with a 2-way safety zipper. Made from stretchy micro-ribbed organic cotton with fold-over mitten cuffs for scratch protection.',
    price: 2150,
    categorySlug: 'sleep-snuggle',
    gender: 'unisex',
    images: ['/products/img25.webp'],
    stock: 32,
    sku: 'BC-SLEEP-025',
    brand: 'Butterfly Care Sleep',
    ageGroup: '0-24 months',
    sizes: ['0-3M', '3-6M', '6-12M', '1-2Y'],
    colors: ['Oatmeal Heather'],
    materials: '95% Organic Cotton, 5% Elastane',
    careInstructions: 'Machine wash warm.',
    rating: 4.9,
    reviewCount: 48,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Vintage Floral Ruffled Pinafore Dress with Bloomer',
    slug: 'vintage-floral-ruffled-pinafore-dress-bloomer',
    shortDescription: 'Antique floral print cotton pinafore dress with matching bloomer shorts.',
    description: 'Charming vintage wildflower print pinafore dress with cross-back ruffled straps and matching bloomer shorts for an adorable complete look.',
    price: 2490,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img26.webp'],
    stock: 14,
    sku: 'BC-GIRL-026',
    brand: 'Butterfly Care Heirloom',
    ageGroup: '0-24 months',
    sizes: ['0-6M', '6-12M', '1-2Y'],
    colors: ['Blush Wildflower'],
    materials: '100% Combed Cotton',
    careInstructions: 'Machine wash cold.',
    rating: 5.0,
    reviewCount: 33,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Baby Boy Nautical Anchor Embroidered Romper',
    slug: 'baby-boy-nautical-anchor-embroidered-romper',
    shortDescription: 'Navy and white polo romper with embroidered anchor and snap fastenings.',
    description: 'Classic nautical cotton romper featuring a ribbed collar, button placket, embroidered navy anchor, and nickel-free leg snaps for easy diaper access.',
    price: 1690,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img27.jpg'],
    stock: 22,
    sku: 'BC-BOY-027',
    brand: 'Butterfly Care Boy',
    ageGroup: '0-18 months',
    sizes: ['0-3M', '3-6M', '6-12M', '12-18M'],
    colors: ['Navy & White'],
    materials: '100% Pique Cotton',
    careInstructions: 'Machine wash cold.',
    rating: 4.8,
    reviewCount: 26,
    featured: false,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Ergonomic Organic Cotton Baby Nursing Pillow',
    slug: 'ergonomic-organic-cotton-baby-nursing-pillow',
    shortDescription: 'Contoured nursing and feeding pillow with washable cotton slipcover.',
    description: 'Designed to relieve back and arm strain during feeding sessions. Provides firm support and comfortable elevation for latching and bottle feeding.',
    price: 5250,
    discountPrice: 4650,
    categorySlug: 'feeding-nursing',
    gender: 'mom',
    images: ['/products/img28.jpg'],
    stock: 16,
    sku: 'BC-FEED-028',
    brand: 'Butterfly Care Cozy',
    ageGroup: '0-12 months',
    sizes: ['Standard Contoured'],
    colors: ['Soft Blossom Grey'],
    materials: 'Hypoallergenic Fiber Fill, 100% Organic Cotton Slipcover',
    careInstructions: 'Removable cover is machine washable.',
    rating: 4.9,
    reviewCount: 42,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Ultra-Soft Cloud Velvet Baby Stroller Blanket',
    slug: 'ultra-soft-cloud-velvet-baby-stroller-blanket',
    shortDescription: 'Plush cloud velvet stroller blanket with dotted sherpa backing.',
    description: 'Luxuriously soft double-sided baby blanket featuring a silky velvet front and cozy textured dotted sherpa fleece backing. Perfect for cribs, strollers, and road trips.',
    price: 2990,
    categorySlug: 'sleep-snuggle',
    gender: 'unisex',
    images: ['/products/img29.jpg'],
    stock: 20,
    sku: 'BC-BL-029',
    brand: 'Butterfly Care Sleep',
    ageGroup: '0-36 months',
    sizes: ['100cm x 110cm'],
    colors: ['Powder Blue & Cream'],
    materials: 'Ultra-fine Microfiber Velvet & Sherpa',
    careInstructions: 'Machine wash cold. Do not iron.',
    rating: 5.0,
    reviewCount: 39,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Gentle Tear-Free Coconut & Calendula Baby Shampoo',
    slug: 'gentle-tear-free-coconut-calendula-baby-shampoo',
    shortDescription: 'Hypoallergenic moisturizing shampoo that leaves fine baby hair silky and soft.',
    description: 'Enriched with virgin coconut oil and organic calendula, this tear-free baby shampoo gently cleanses fine infant hair without stripping natural scalp moisture.',
    price: 1750,
    categorySlug: 'bath-care',
    gender: 'unisex',
    images: ['/products/img30.jpg'],
    stock: 25,
    sku: 'BC-BATH-030',
    brand: 'Butterfly Care Pure',
    ageGroup: '0+ months',
    sizes: ['250ml'],
    colors: ['Natural White'],
    materials: 'Virgin Coconut Oil, Organic Calendula, Plant Glucosides',
    careInstructions: 'Apply small amount to wet hair, gently lather and rinse.',
    rating: 4.8,
    reviewCount: 28,
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Delicate Broderie Anglaise Baby Girl Party Frock',
    slug: 'delicate-broderie-anglaise-baby-girl-party-frock',
    shortDescription: 'Intricate eyelet embroidered cotton celebration dress with scalloped hem.',
    description: 'Exquisite cotton broderie anglaise party dress featuring scalloped flutter sleeves, an Empire waist with satin sash, and breathable cotton lining.',
    price: 3550,
    discountPrice: 3150,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img31.jpg'],
    stock: 12,
    sku: 'BC-GIRL-031',
    brand: 'Butterfly Care Occasions',
    ageGroup: '3-36 months',
    sizes: ['3-6M', '6-12M', '1-2Y', '2-3Y'],
    colors: ['Ivory Petal'],
    materials: '100% Broderie Cotton with Soft Cotton Voile Lining',
    careInstructions: 'Hand wash cold or gentle cycle inside a garment bag.',
    rating: 5.0,
    reviewCount: 36,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Smart Safari Animal Print Baby Boy Play Set',
    slug: 'smart-safari-animal-print-baby-boy-play-set',
    shortDescription: '2-piece safari tee and stretch twill shorts set for active toddlers.',
    description: 'Playful two-piece ensemble featuring a lightweight slub cotton t-shirt with safari animal illustrations and matching elasticated pull-on twill shorts.',
    price: 2050,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img32.jpg'],
    stock: 20,
    sku: 'BC-BOY-032',
    brand: 'Butterfly Care Boy',
    ageGroup: '6-48 months',
    sizes: ['6-12M', '1-2Y', '2-3Y', '3-4Y'],
    colors: ['Safari Khaki'],
    materials: '100% Slub Cotton Top & Chino Shorts',
    careInstructions: 'Machine wash warm.',
    rating: 4.9,
    reviewCount: 30,
    featured: false,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Organic Lanolin-Free Herbal Nipple Soothing Balm',
    slug: 'organic-lanolin-free-herbal-nipple-soothing-balm',
    shortDescription: 'Food-grade plant butter balm that soothes tender nursing skin without washing off.',
    description: 'Formulated with organic shea butter, calendula-infused olive oil, and mango seed butter. 100% safe for baby nursing without needing to be washed off.',
    price: 1890,
    categorySlug: 'mom-care',
    gender: 'mom',
    images: ['/products/img33.jpg'],
    stock: 30,
    sku: 'BC-NB-033',
    brand: 'Butterfly Care Mama',
    ageGroup: 'Nursing Moms',
    sizes: ['50g'],
    colors: ['Golden Honey'],
    materials: 'Organic Shea Butter, Mango Butter, Calendula, Olive Oil',
    careInstructions: 'Apply a pea-sized amount after nursing.',
    rating: 5.0,
    reviewCount: 45,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Silicone Ergonomic Baby Feeding Spoon & Bib Set',
    slug: 'silicone-ergonomic-baby-feeding-spoon-bib-set',
    shortDescription: '100% food grade BPA-free soft silicone bib with deep catch pocket and training spoon.',
    description: 'Mess-free weening starter bundle: adjustable soft silicone bib with spill catcher pocket paired with a gentle silicone gum-friendly training spoon.',
    price: 1650,
    categorySlug: 'feeding-nursing',
    gender: 'unisex',
    images: ['/products/img34.jpg'],
    stock: 28,
    sku: 'BC-FEED-034',
    brand: 'Butterfly Care Feeding',
    ageGroup: '4-24 months',
    sizes: ['Starter Duo'],
    colors: ['Muted Sage & Sand'],
    materials: '100% Food-Grade Platinum Silicone (BPA, PVC & Phthalate Free)',
    careInstructions: 'Dishwasher and sterilizer safe.',
    rating: 4.9,
    reviewCount: 38,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Breathable Cotton Cellular Newborn Blanket Duo',
    slug: 'breathable-cotton-cellular-newborn-blanket-duo',
    shortDescription: 'Open-weave cellular structure blankets for hospital bags and cribs (2-Pack).',
    description: 'Hospital bag essential pack of 2 open-cell 100% cotton blankets that allow airflow while trapping warm air for safe temperature regulation.',
    price: 2750,
    categorySlug: 'sleep-snuggle',
    gender: 'unisex',
    images: ['/products/img35.webp'],
    stock: 24,
    sku: 'BC-BL-035',
    brand: 'Butterfly Care Sleep',
    ageGroup: '0-24 months',
    sizes: ['90cm x 100cm'],
    colors: ['Cloud White & Oat'],
    materials: '100% Pure Combed Cotton',
    careInstructions: 'Machine wash warm.',
    rating: 4.8,
    reviewCount: 31,
    featured: false,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Sweet Strawberry Embroidered Baby Girl Romper',
    slug: 'sweet-strawberry-embroidered-baby-girl-romper',
    shortDescription: 'Pink and white stripe cotton romper with embroidered strawberry patch.',
    description: 'Adorable cotton summer romper with delicate strawberry chest embroidery, flutter ruffled cap sleeves, and nickel-free bottom snap buttons.',
    price: 1590,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img36.webp'],
    stock: 18,
    sku: 'BC-GIRL-036',
    brand: 'Butterfly Care',
    ageGroup: '0-18 months',
    sizes: ['0-3M', '3-6M', '6-12M', '12-18M'],
    colors: ['Strawberry Pink'],
    materials: '100% Soft Cotton Jersey',
    careInstructions: 'Machine wash cold.',
    rating: 4.9,
    reviewCount: 27,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Cozy Waffle Knit Baby Boy Jumpsuit with Wooden Buttons',
    slug: 'cozy-waffle-knit-baby-boy-jumpsuit',
    shortDescription: 'Textured thermal waffle knit romper with Henley button neckline.',
    description: 'Ultra-soft thermal waffle knit one-piece jumpsuit featuring natural coconut wood buttons and stretchy cuffs that grow with your baby.',
    price: 2390,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img37.jpg'],
    stock: 22,
    sku: 'BC-BOY-037',
    brand: 'Butterfly Care Boy',
    ageGroup: '0-24 months',
    sizes: ['0-3M', '3-6M', '6-12M', '1-2Y'],
    colors: ['Slate Blue'],
    materials: '95% Waffle Cotton, 5% Spandex',
    careInstructions: 'Machine wash cold with like colors.',
    rating: 5.0,
    reviewCount: 34,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Postpartum Herbal Sitz Bath Recovery Soak',
    slug: 'postpartum-herbal-sitz-bath-recovery-soak',
    shortDescription: 'Organic herbal bath blend with Epsom salts, Dead Sea salt, and Lavender.',
    description: 'A comforting, rejuvenating traditional sitz bath blend designed to accelerate perineal healing, soothe postpartum soreness, and provide profound relaxation.',
    price: 2350,
    categorySlug: 'mom-care',
    gender: 'mom',
    images: ['/products/img38.jpg'],
    stock: 18,
    sku: 'BC-MOM-038',
    brand: 'Butterfly Care Mama',
    ageGroup: 'Postpartum Moms',
    sizes: ['300g (6 Soaks)'],
    colors: ['Herbal Botanical'],
    materials: 'Dead Sea Salt, Epsom Salt, Lavender Buds, Witch Hazel, Calendula',
    careInstructions: 'Steep in hot water and pour into warm bath or sitz pan.',
    rating: 4.9,
    reviewCount: 40,
    featured: false,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Natural Sheep Wool Bristle Baby Hair Brush & Comb Set',
    slug: 'natural-sheep-wool-bristle-baby-hair-brush-comb-set',
    shortDescription: 'Ultra-soft natural wool grooming brush designed to gently prevent cradle cap.',
    description: 'Handmade beechwood baby grooming kit with super-soft natural sheep wool bristles that gently stimulate hair growth and soothe cradle cap.',
    price: 1490,
    categorySlug: 'baby-essentials',
    gender: 'unisex',
    images: ['/products/img39.jpg'],
    stock: 30,
    sku: 'BC-ESS-039',
    brand: 'Butterfly Care Pure',
    ageGroup: '0-36 months',
    sizes: ['Brush + Comb Set'],
    colors: ['Natural Beechwood'],
    materials: 'Natural Beechwood & 100% Pure Goat Wool Bristles',
    careInstructions: 'Clean bristles with mild soap and warm water.',
    rating: 4.9,
    reviewCount: 33,
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Organic Cotton Muslin Bandana Dribble Bibs (4-Pack)',
    slug: 'organic-cotton-muslin-bandana-dribble-bibs-4-pack',
    shortDescription: 'Pack of 4 absorbent triangular muslin bibs with adjustable snap fasteners.',
    description: 'Keep teething babies dry and stylish. Features 3 layers of soft organic muslin cotton with nickel-free snaps for adjustable sizing.',
    price: 1950,
    discountPrice: 1650,
    categorySlug: 'baby-essentials',
    gender: 'unisex',
    images: ['/products/img40.jpg'],
    stock: 35,
    sku: 'BC-ESS-040',
    brand: 'Butterfly Care Basics',
    ageGroup: '0-24 months',
    sizes: ['Pack of 4'],
    colors: ['Neutral Earth Palette'],
    materials: '100% GOTS Organic Cotton Muslin',
    careInstructions: 'Machine wash cold.',
    rating: 4.9,
    reviewCount: 47,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Enchanted Garden Floral Smocked Twirl Dress',
    slug: 'enchanted-garden-floral-smocked-twirl-dress',
    shortDescription: 'Vibrant botanical floral print party dress with hand-smocked chest and puff sleeves.',
    description: 'Full-circle twirl dress crafted from crisp cotton poplin adorned with garden blossoms, intricate hand-smocked chest embroidery, and bow tie back.',
    price: 2790,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img41.webp'],
    stock: 14,
    sku: 'BC-GIRL-041',
    brand: 'Butterfly Care Heirloom',
    ageGroup: '6-48 months',
    sizes: ['6-12M', '1-2Y', '2-3Y', '3-4Y'],
    colors: ['Garden Rose Bloom'],
    materials: '100% Fine Combed Cotton',
    careInstructions: 'Machine wash cold inside out.',
    rating: 5.0,
    reviewCount: 38,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Dapper Baby Boy Linen Vest & Chino Shorts Set',
    slug: 'dapper-baby-boy-linen-vest-chino-shorts-set',
    shortDescription: 'Formal occasion buttoned linen waistcoat with crisp white shirt and tailored shorts.',
    description: 'Charming 3-piece formal celebration set featuring a tailored linen waistcoat, breathable white cotton shirt, and matching chino shorts with belt loops.',
    price: 3450,
    discountPrice: 2990,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img42.jpg'],
    stock: 16,
    sku: 'BC-BOY-042',
    brand: 'Butterfly Care Occasions',
    ageGroup: '6-48 months',
    sizes: ['6-12M', '1-2Y', '2-3Y', '3-4Y'],
    colors: ['Beige & White Linen'],
    materials: '55% Linen, 45% Cotton',
    careInstructions: 'Gentle cycle wash or dry clean.',
    rating: 4.9,
    reviewCount: 29,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Handcrafted Bunny Heirloom Soft Plush Toy',
    slug: 'handcrafted-bunny-heirloom-soft-plush-toy',
    shortDescription: 'Hand-stitched organic cotton cuddly bunny plushie with floppy ears.',
    description: 'Safe for newborns from day one. Handcrafted from organic cotton knit and filled with hypoallergenic corn fiber. A comforting snuggle companion for years.',
    price: 1690,
    categorySlug: 'toys-gifts',
    gender: 'unisex',
    images: ['/products/img43.png'],
    stock: 25,
    sku: 'BC-TOY-043',
    brand: 'Butterfly Care Gift',
    ageGroup: '0+ months',
    sizes: ['30cm Tall'],
    colors: ['Oatmeal Bunny'],
    materials: '100% Organic Cotton Knit & Hypoallergenic Fill',
    careInstructions: 'Spot clean or hand wash cold.',
    rating: 5.0,
    reviewCount: 51,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Organic Zinc Oxide Calming Nappy Cream (120g)',
    slug: 'organic-zinc-oxide-calming-nappy-cream',
    shortDescription: 'Clinically proven barrier cream that protects and soothes diaper rash naturally.',
    description: 'Forms a breathable protective layer against moisture. Packed with 15% non-nano zinc oxide, organic coconut oil, and soothing aloe vera.',
    price: 1650,
    categorySlug: 'bath-care',
    gender: 'unisex',
    images: ['/products/img44.jpg'],
    stock: 35,
    sku: 'BC-BATH-044',
    brand: 'Butterfly Care Pure',
    ageGroup: '0-24 months',
    sizes: ['120g Tub'],
    colors: ['White Cream'],
    materials: 'Non-nano Zinc Oxide, Organic Coconut Oil, Shea Butter',
    careInstructions: 'Apply liberally at every diaper change.',
    rating: 4.9,
    reviewCount: 44,
    featured: false,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Pure Linen Motherhood Postpartum Nursing Robe',
    slug: 'pure-linen-motherhood-postpartum-nursing-robe',
    shortDescription: 'Breathable stonewashed French linen maternity robe with adjustable sash.',
    description: 'Wrap yourself in airy, stonewashed French linen. Designed with deep pockets, easy feeding crossover neckline, and a relaxed silhouette for effortless postpartum elegance.',
    price: 5650,
    discountPrice: 4950,
    categorySlug: 'mom-care',
    gender: 'mom',
    images: ['/products/img45.webp'],
    stock: 12,
    sku: 'BC-MOM-045',
    brand: 'Butterfly Care Mama',
    ageGroup: 'Mothers',
    sizes: ['S/M', 'L/XL'],
    colors: ['Dusty Rose Linen'],
    materials: '100% French Stonewashed Linen',
    careInstructions: 'Machine wash cold. Line dry in shade.',
    rating: 5.0,
    reviewCount: 36,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Pastel Polka Dot Ruffle Baby Girl Romper with Bow',
    slug: 'pastel-polka-dot-ruffle-baby-girl-romper',
    shortDescription: 'Sweet polka dot bubble romper with cross back ruffle straps and matching headband.',
    description: 'Charming vintage bubble romper with delicate polka dots, ruffled shoulder wings, elasticated leg openings, and an adorable matching stretch bow headband.',
    price: 1490,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img46.webp'],
    stock: 20,
    sku: 'BC-GIRL-046',
    brand: 'Butterfly Care',
    ageGroup: '0-24 months',
    sizes: ['0-3M', '3-6M', '6-12M', '1-2Y'],
    colors: ['Pastel Peach Polka'],
    materials: '100% Soft Combed Cotton',
    careInstructions: 'Machine wash cold.',
    rating: 4.8,
    reviewCount: 25,
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Organic Cotton Striped Bear Pocket Baby Overalls',
    slug: 'organic-cotton-striped-bear-pocket-baby-overalls',
    shortDescription: 'Cozy striped cotton overalls with front kangaroo pocket and button straps.',
    description: 'Everyday play overalls featuring subtle Breton stripes, adjustable shoulder button straps, and snap closures along the inseam for speedy diaper changes.',
    price: 2250,
    categorySlug: 'clothing',
    gender: 'boy',
    images: ['/products/img47.webp'],
    stock: 22,
    sku: 'BC-BOY-047',
    brand: 'Butterfly Care Boy',
    ageGroup: '0-24 months',
    sizes: ['0-6M', '6-12M', '1-2Y'],
    colors: ['Oat & Slate Stripe'],
    materials: '100% Heavyweight Cotton Jersey',
    careInstructions: 'Machine wash warm.',
    rating: 4.9,
    reviewCount: 31,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Luxury Newborn Welcome Keepsake Hamper Basket',
    slug: 'luxury-newborn-welcome-keepsake-hamper-basket',
    shortDescription: 'Curated deluxe gift basket with baby blanket, toys, skincare, and milestone cards.',
    description: 'The ultimate baby shower gift: woven keepsake basket containing a dream swaddle, plush bunny, organic body wash, baby massage oil, and wooden milestone discs.',
    price: 6750,
    discountPrice: 5950,
    categorySlug: 'toys-gifts',
    gender: 'unisex',
    images: ['/products/img48.webp'],
    stock: 10,
    sku: 'BC-GIFT-048',
    brand: 'Butterfly Care Gift',
    ageGroup: '0-12 months',
    sizes: ['Deluxe Hamper Set'],
    colors: ['Neutral Golden Sun'],
    materials: 'Woven Cotton Rope Basket & Organic Essentials',
    careInstructions: 'Store in dry place.',
    rating: 5.0,
    reviewCount: 42,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Thermal Insulated Portable Baby Milk Bottle Bag',
    slug: 'thermal-insulated-portable-baby-milk-bottle-bag',
    shortDescription: 'Insulated waterproof thermal pouch that keeps bottles warm or cool for 4+ hours.',
    description: 'Compact travel companion featuring triple-layer thermal foil insulation, waterproof exterior, and a snap-button strap that clips directly onto strollers.',
    price: 1750,
    categorySlug: 'feeding-nursing',
    gender: 'unisex',
    images: ['/products/img49.jpg'],
    stock: 26,
    sku: 'BC-FEED-049',
    brand: 'Butterfly Care Feeding',
    ageGroup: 'All Ages',
    sizes: ['Double Bottle Size'],
    colors: ['Soft Grey Melange'],
    materials: 'Waterproof Oxford Cloth & Thermal Aluminum Foil',
    careInstructions: 'Wipe clean with a damp cloth.',
    rating: 4.8,
    reviewCount: 23,
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Calming Lavender & Chamomile Sleep Pillow Mist (100ml)',
    slug: 'calming-lavender-chamomile-sleep-pillow-mist',
    shortDescription: 'Aromatherapeutic nursery & pillow mist for relaxing bedtime bedtime routines.',
    description: 'Crafted with therapeutic grade French lavender and Roman chamomile essential waters. Spritz gently on nursery curtains or bedding to invite restful deep sleep.',
    price: 1690,
    categorySlug: 'sleep-snuggle',
    gender: 'unisex',
    images: ['/products/img50.jpg'],
    stock: 30,
    sku: 'BC-SLEEP-050',
    brand: 'Butterfly Care Sleep',
    ageGroup: '0+ months',
    sizes: ['100ml Spray'],
    colors: ['Calm Lavender'],
    materials: 'Distilled Water, French Lavender Hydrosol, Chamomile Flower Extract',
    careInstructions: 'Spray in the room or on bedding 10 minutes before bedtime.',
    rating: 4.9,
    reviewCount: 35,
    featured: false,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Vintage Lace Trimmed Baby Girl Christening Dress',
    slug: 'vintage-lace-trimmed-baby-girl-christening-dress',
    shortDescription: 'Pure white heirloom baptism gown with embroidered tulle overlay and bonnet.',
    description: 'Breathtaking pure white christening dress crafted from silky cotton with French floral lace overlay, delicate ribbon bow, and matching lace bonnet.',
    price: 4250,
    discountPrice: 3650,
    categorySlug: 'clothing',
    gender: 'girl',
    images: ['/products/img51.jpg'],
    stock: 10,
    sku: 'BC-GIRL-051',
    brand: 'Butterfly Care Occasions',
    ageGroup: '0-18 months',
    sizes: ['0-3M', '3-6M', '6-12M', '12-18M'],
    colors: ['Pure White Lace'],
    materials: 'French Floral Lace & 100% Combed Cotton Lining',
    careInstructions: 'Dry clean or gentle hand wash cold.',
    rating: 5.0,
    reviewCount: 29,
    featured: true,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Cozy Fleece Lined Winter Booties & Mitten Duo',
    slug: 'cozy-fleece-lined-winter-booties-mitten-duo',
    shortDescription: 'Faux shearling booties with non-slip grippers and warm fleece mittens.',
    description: 'Keep tiny toes and fingers toasty warm. Features soft fleece lining, adjustable Velcro closures on booties that stay securely on wiggly feet.',
    price: 1450,
    categorySlug: 'baby-essentials',
    gender: 'unisex',
    images: ['/products/img52.webp'],
    stock: 28,
    sku: 'BC-ESS-052',
    brand: 'Butterfly Care Cozy',
    ageGroup: '0-18 months',
    sizes: ['0-6M', '6-12M', '12-18M'],
    colors: ['Teddy Tan'],
    materials: 'Ultra-soft Faux Shearling & Fleece',
    careInstructions: 'Machine wash cold on delicate cycle.',
    rating: 4.8,
    reviewCount: 24,
    featured: false,
    bestSeller: false,
    newArrival: true,
    active: true
  },
  {
    name: 'Hypoallergenic Bamboo Baby Wipes (Pack of 3 x 80s)',
    slug: 'hypoallergenic-bamboo-baby-wipes-3-pack',
    shortDescription: '99% pure water wipes made with 100% biodegradable unbleached bamboo fibers.',
    description: 'Super-soft, extra-thick unbleached bamboo wipes formulated with pure water, aloe vera, and cucumber extract. Fragrance-free and safe for newborn faces and hands.',
    price: 2490,
    discountPrice: 2190,
    categorySlug: 'baby-essentials',
    gender: 'unisex',
    images: ['/products/img53.jpg'],
    stock: 40,
    sku: 'BC-ESS-053',
    brand: 'Butterfly Care Pure',
    ageGroup: '0+ months',
    sizes: ['3 Packs (240 Wipes)'],
    colors: ['Pure Fresh'],
    materials: '100% Biodegradable Bamboo Fiber, 99% Purified Water',
    careInstructions: 'Reseal flip-top lid tightly after each use.',
    rating: 4.9,
    reviewCount: 62,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  },
  {
    name: 'Motherhood Hydrating Botanical Face & Neck Elixir (50ml)',
    slug: 'motherhood-hydrating-botanical-face-neck-elixir',
    shortDescription: 'Pregnancy-safe rejuvenating serum with Hyaluronic Acid and Squalane.',
    description: 'Restore radiant, tired skin naturally. Formulated with plant squalane, multi-molecular hyaluronic acid, and organic rose flower water for deep, lasting hydration.',
    price: 3750,
    discountPrice: 3250,
    categorySlug: 'mom-care',
    gender: 'mom',
    images: ['/products/img54.jpg'],
    stock: 18,
    sku: 'BC-MOM-054',
    brand: 'Butterfly Care Mama',
    ageGroup: 'Mothers',
    sizes: ['50ml Dropper'],
    colors: ['Rose Petal Glow'],
    materials: 'Plant Squalane, Hyaluronic Acid, Rose Hydrosol, Niacinamide',
    careInstructions: 'Apply 3-4 drops to cleansed face and neck morning and night.',
    rating: 5.0,
    reviewCount: 38,
    featured: true,
    bestSeller: true,
    newArrival: true,
    active: true
  }
];

export const INITIAL_REVIEWS = [
  {
    productSku: 'BC-GIFT-001',
    userName: 'Dilani Perera',
    userEmail: 'dilani.p@gmail.com',
    rating: 5,
    title: 'Pure magic for my baby’s sensitive skin!',
    comment: 'I was hesitant to try new products on my 2-month-old daughter who had mild eczema, but this wash is exceptionally gentle. Soft subtle fragrance and zero redness!',
    verifiedPurchase: true,
    status: 'approved'
  },
  {
    productSku: 'BC-MO-022',
    userName: 'Kavindi Jayawardena',
    userEmail: 'kavindi.j@yahoo.com',
    rating: 5,
    title: 'Must-have for every expecting mother',
    comment: 'Used this belly oil throughout my entire second pregnancy and not a single new stretch mark appeared. Smells like a luxury spa and absorbs so quickly.',
    verifiedPurchase: true,
    status: 'approved'
  },
  {
    productSku: 'BC-SW-019',
    userName: 'Sarah Fernando',
    userEmail: 'sarah.f@outlook.com',
    rating: 5,
    title: 'Incredible quality and gorgeous packaging',
    comment: 'These muslin swaddles are hands down the softest we own in Sri Lanka. They wash beautifully without shrinking and the butterfly motif is so lovely.',
    verifiedPurchase: true,
    status: 'approved'
  },
  {
    productSku: 'BC-FEED-028',
    userName: 'Thilini Senanayake',
    userEmail: 'thilini.s@gmail.com',
    rating: 5,
    title: 'Saved my posture during breastfeeding',
    comment: 'The memory foam support makes such a massive difference compared to regular soft pillows. Delivery to Kandy took only 2 days. Highly recommended!',
    verifiedPurchase: true,
    status: 'approved'
  },
  {
    productSku: 'BC-SLEEP-025',
    userName: 'Anushka De Silva',
    userEmail: 'anushka.ds@gmail.com',
    rating: 5,
    title: 'The two-way zipper is a lifesaver at night',
    comment: 'The organic ribbed cotton feels like butter! Midnight diaper changes are so seamless now without waking my baby completely. Ordering more colors today.',
    verifiedPurchase: true,
    status: 'approved'
  },
  {
    productSku: 'BC-GIFT-048',
    userName: 'Rochelle Mendis',
    userEmail: 'rochelle.m@gmail.com',
    rating: 5,
    title: 'Brought tears of joy at the baby shower',
    comment: 'Sent this gift box to my sister in Colombo. The presentation was royal and the quality of each item inside is top tier. Butterfly Care is my new go-to brand.',
    verifiedPurchase: true,
    status: 'approved'
  }
];

export const INITIAL_COUPONS = [
  {
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 3000,
    maxDiscount: 1500,
    usageLimit: 500,
    usedCount: 14,
    active: true
  },
  {
    code: 'MOMCARE500',
    discountType: 'fixed',
    discountValue: 500,
    minOrderValue: 5000,
    usageLimit: 200,
    usedCount: 8,
    active: true
  },
  {
    code: 'FREESHIP',
    discountType: 'fixed',
    discountValue: 450,
    minOrderValue: 4000,
    usageLimit: 300,
    usedCount: 19,
    active: true
  }
];

export const INITIAL_USERS = [
  {
    name: 'Butterfly Admin',
    email: 'admin@butterflycare.com',
    password: 'Admin@123456',
    role: 'admin',
    phone: '+94771234567',
    addresses: [
      {
        fullName: 'Butterfly Care Admin HQ',
        phone: '+94771234567',
        addressLine: '42 Lotus Avenue',
        city: 'Colombo',
        district: 'Colombo',
        postalCode: '00700',
        isDefault: true
      }
    ]
  },
  {
    name: 'Dilani Perera',
    email: 'dilani.p@gmail.com',
    password: 'Customer@123',
    role: 'customer',
    phone: '0712345678',
    addresses: [
      {
        fullName: 'Dilani Perera',
        phone: '0712345678',
        addressLine: '15/3 Flower Road',
        city: 'Colombo 03',
        district: 'Colombo',
        postalCode: '00300',
        isDefault: true
      }
    ]
  },
  {
    name: 'Kavindi Jayawardena',
    email: 'kavindi.j@yahoo.com',
    password: 'Customer@123',
    role: 'customer',
    phone: '0772345679',
    addresses: [
      {
        fullName: 'Kavindi Jayawardena',
        phone: '0772345679',
        addressLine: '88 Negombo Road',
        city: 'Wattala',
        district: 'Gampaha',
        postalCode: '11300',
        isDefault: true
      }
    ]
  }
];
